version: 2
builds:

- id: "kagenti-webhook"
  dir: kagenti-webhook
  main: ./cmd
  binary: manager
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: ppc64le
  env:
  - CGO_ENABLED=0

archives:
- ids: [kagenti-webhook]

kos:
  - id: "kagenti-webhook-ko"
    repositories:
    - ghcr.io/kagenti/kagenti-extensions/kagenti-webhook
    working_dir: kagenti-webhook
    main: ./cmd
    build: kagenti-webhook
    tags:
      - '{{.Version}}'
      - latest
    bare: false
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
    env:
      - CGO_ENABLED=0
release:
  draft: false
  prerelease: auto
  mode: keep-existing
