matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .github/spellcheck/.wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown: {}
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - '**/*.md'
    default_encoding: utf-8

  - name: Text
    aspell:
      lang: en
    dictionary:
      wordlists:
        - .github/spellcheck/.wordlist.txt
      encoding: utf-8
    pipeline:
      - pyspelling.filters.text: {}
    sources:
      - '**/*.txt'
    default_encoding: utf-8
